### PR TITLE
Fix HTML sanitizer crash.

### LINKED ISSUE #42: Fix html sanitizer crash
The html sanitizer crashes on the string:

```
<??/N>
```

### PR DESCRIPTION
**Pull request by mworrell**
Fix #42

 * Fix crash when parsing `<??/N>`
 * Change return format of z_html_parse:parse/1
 * Add type specs for dialyzer.
 * Let Makefile use GNUMakefile
 * Add eunit test to GNUMakefile

### CODE REVIEW

**Comment by mmzeeman** [comment]
Aha... api change... for really really bad html...

**Comment by mworrell** [comment]
Indeed - this was an interesting construct, and we should be able to throw anything at these routines.

**Comment by mmzeeman** [comment]
Maybe we could make a property based test for the routines. Just like what was done for the utf-8 routines.

**Comment by mworrell** [comment]
Yes, a property model would be nice.

Though we can call the sanitize exceptionally stable, having seen only a single problem when throwing the dataset of 500K emails at it.

**Pull request merged**
