### PR TITLE
Fix z_string encoding and add missing chars

### PR DESCRIPTION
**Pull request by williamthome**
This PR fixes issues using `to_upper`, `to_lower`, and `normalize` functions from the `z_string` module.
For example:
```console
1> <<"NOTIFICAÇÕES"/utf8>> = z_string:to_upper(<<"notificações"/utf8>>).
** exception error: no match of right hand side value <<"NOTIFICAÇõES"/utf8>>
2> <<"notificações"/utf8>> = z_string:to_lower(<<"NOTIFICAÇÕES"/utf8>>).
** exception error: no match of right hand side value <<"notificaçÕes"/utf8>>
3> <<"notificações"/utf8>> = z_string:normalize(<<"NOTIFICAÇÕES"/utf8>>).
** exception error: no match of right hand side value <<"notificacÕes"/utf8>>
```

Also, I added tests to all chars (the unique not tested is the 8023 because I don't know how) from the `normalize` function.
Maybe the `binary()` and `string()` tests can be unified as `iodata()`, but I created both tests for both.
Some tests are falling for Hebrew. Falling testes are commented.
There is a note where tests are unsuccessful:
```erlang
% FIXME: commented checks are falling
```

* Notificações in pt-BR means notifications.

### CODE REVIEW

**Comment by williamthome** [comment]
`string()` instead of `list()` will be valid?
```erlang
-type string() :: [char()].
-type char() :: 0..16#10FFFF.
```

**Comment by williamthome** [comment]
Strange that in my machine dialyzer doesn't fail.
I will push a commit changing the spec and then you give me your thoughts.
If it's not fine I will revert it.

**Comment by mworrell** [comment]
I agree with the `string()`.

With Zotonic 1.x we git rid of the uff-8 lists of bytes, so we can assume strings are character data.

Depending if we use `unicode` to make it a binary we might want to use `unicode:chardata()` as a type.

At some point in the future we might also check the unicode compatible `string:casefold/1` and remove our custom implementation.

**Comment by mworrell** [comment]
Thanks!

**Comment by williamthome** [comment]
No urgency, no problem waiting some time to get this change.
Also, thanks! All the best.

**Pull request merged**
