### PR TITLE
Publish to Hex using erlangpack/github-action

### PR DESCRIPTION
**Pull request by ddeboer**

### CODE REVIEW

**Comment by mworrell** [comment]
Do you think it is possible to add an action-option to publish the edocs?

**Comment by ddeboer** [comment]
Is that just a matter of `rebar3 hex docs`?

**Comment by mworrell** [comment]
Yes :-)

**Comment by mworrell** [comment]
Then you get something like here:

https://hex.pm/packages/zotonic_ssl

You need to publish the docs that match the current published tag.

**Pull request merged**
